In [1]:
import pandas as pd
import zipfile
import duckdb

In [ ]:

con = duckdb.connect("../data/sepa.db")

tablas = con.execute("SHOW TABLES").df()

for tabla in tablas["name"]:import zipfile
import pandas as pd

with zipfile.ZipFile("../data/sepa_viernes.zip", "r") as zip_principal:
    zips_internos = [f for f in zip_principal.namelist() if f.endswith(".zip")]
    
    # Abrimos solo el primero para inspeccionar
    with zip_principal.open(zips_internos[0]) as archivo_virtual:
        with zipfile.ZipFile(archivo_virtual) as zip_interno:
            csv_productos = [n for n in zip_interno.namelist() if "productos" in n.lower()][0]
            
            with zip_interno.open(csv_productos) as f:
                df = pd.read_csv(f, sep="|", nrows=2)  # solo 2 filas para ver estructura
                print("Columnas reales:", df.columns.tolist())
                print(df)
    
    print(f"tabla: {tabla}")
    print(con.execute(f"DESCRIBE {tabla}").df())
    print("##########################")

tabla: comercios
                     column_name column_type null   key default extra
0                    id_comercio     VARCHAR  YES  None    None  None
1                     id_bandera     VARCHAR  YES  None    None  None
2                  comercio_cuit      DOUBLE  YES  None    None  None
3          comercio_razon_social     VARCHAR  YES  None    None  None
4        comercio_bandera_nombre     VARCHAR  YES  None    None  None
5           comercio_bandera_url     VARCHAR  YES  None    None  None
6  comercio_ultima_actualizacion     VARCHAR  YES  None    None  None
7          comercio_version_sepa      DOUBLE  YES  None    None  None
##########################
tabla: precios
             column_name column_type null   key default extra
0          productos_ean     VARCHAR  YES  None    None  None
1            id_comercio     VARCHAR  YES  None    None  None
2             id_bandera     VARCHAR  YES  None    None  None
3            id_sucursal     VARCHAR  YES  None    None  None
4  productos_descripcion     VARCHAR  YES  None    None  None
##########################
tabla: sucursales
         column_name column_type null   key default extra
0        id_comercio     VARCHAR  YES  None    None  None
1         id_bandera     VARCHAR  YES  None    None  None
2        id_sucursal     VARCHAR  YES  None    None  None
3  sucursales_nombre     VARCHAR  YES  None    None  None
4    sucursales_tipo     VARCHAR  YES  None    None  None
5   sucursales_calle     VARCHAR  YES  None    None  None
6  sucursales_numero     VARCHAR  YES  None    None  None
##########################

In [19]:
con.close()  # cerrá la conexión que abriste con duckdb.connect()

In [18]:
import zipfile
import pandas as pd

with zipfile.ZipFile("../data/sepa_viernes.zip", "r") as zip_principal:
    zips_internos = [f for f in zip_principal.namelist() if f.endswith(".zip")]
    
    # Abrimos solo el primero para inspeccionar
    with zip_principal.open(zips_internos[0]) as archivo_virtual:
        with zipfile.ZipFile(archivo_virtual) as zip_interno:
            csv_productos = [n for n in zip_interno.namelist() if "productos" in n.lower()][0]
            
            with zip_interno.open(csv_productos) as f:
                df = pd.read_csv(f, sep="|", nrows=2)  # solo 2 filas para ver estructura
                print("Columnas reales:", df.columns.tolist())
                print(df)

FileNotFoundError: [Errno 2] No such file or directory: '../data/sepa_viernes.zip'

In [9]:
df_productos = pd.read_csv("productos.csv", sep ="|")
#df_productos["productos_precio_unitario_promo1"].value_counts()
df_productos.columns

C:\Users\user\AppData\Local\Temp\ipykernel_15028\2866059467.py:1: DtypeWarning: Columns (0: id_comercio) have mixed types. Specify dtype option on import or set low_memory=False.
  df_productos = pd.read_csv("productos.csv", sep ="|")

Index(['id_comercio', 'id_bandera', 'id_sucursal', 'id_producto',
       'productos_ean', 'productos_descripcion',
       'productos_cantidad_presentacion',
       'productos_unidad_medida_presentacion', 'productos_marca',
       'productos_precio_lista', 'productos_precio_referencia',
       'productos_cantidad_referencia', 'productos_unidad_medida_referencia',
       'productos_precio_unitario_promo1', 'productos_leyenda_promo1',
       'productos_precio_unitario_promo2', 'productos_leyenda_promo2'],
      dtype='str')

In [ ]:
df_sucursales = pd.read_csv("sucursales.csv", sep ="|")
df_sucursales.columns

Index(['id_comercio', 'id_bandera', 'comercio_cuit', 'comercio_razon_social',
       'comercio_bandera_nombre', 'comercio_bandera_url',
       'comercio_ultima_actualizacion', 'comercio_version_sepa'],
      dtype='str')

In [15]:
df_productos_original = pd.read_csv("productos.csv", sep="|")
df_productos_original.head()

C:\Users\user\AppData\Local\Temp\ipykernel_4128\488262559.py:1: DtypeWarning: Columns (0: id_comercio) have mixed types. Specify dtype option on import or set low_memory=False.
  df_productos_original = pd.read_csv("productos.csv", sep="|")

,id_comercio,id_bandera,id_sucursal,id_producto,productos_ean,productos_descripcion,productos_cantidad_presentacion,productos_unidad_medida_presentacion,productos_marca,productos_precio_lista,productos_precio_referencia,productos_cantidad_referencia,productos_unidad_medida_referencia,productos_precio_unitario_promo1,productos_leyenda_promo1,productos_precio_unitario_promo2,productos_leyenda_promo2
0,12,1.0,170.0,7.798142e+12,1.0,VINO MALBEC EUGENIO BUSTOS LEY BOT 750 ML,750.0,ml,E. BUSTOS LEY,7300.0,9733.33,1.0,ltr,NaN,NaN,NaN,NaN
1,12,1.0,171.0,7.798142e+12,1.0,VINO MALBEC EUGENIO BUSTOS LEY BOT 750 ML,750.0,ml,E. BUSTOS LEY,7300.0,9733.33,1.0,ltr,NaN,NaN,NaN,NaN
2,12,1.0,174.0,7.798142e+12,1.0,VINO MALBEC EUGENIO BUSTOS LEY BOT 750 ML,750.0,ml,E. BUSTOS LEY,7300.0,9733.33,1.0,ltr,NaN,NaN,NaN,NaN
3,12,1.0,176.0,7.798142e+12,1.0,VINO MALBEC EUGENIO BUSTOS LEY BOT 750 ML,750.0,ml,E. BUSTOS LEY,7300.0,9733.33,1.0,ltr,NaN,NaN,NaN,NaN
4,12,1.0,178.0,7.798142e+12,1.0,VINO MALBEC EUGENIO BUSTOS LEY BOT 750 ML,750.0,ml,E. BUSTOS LEY,7300.0,9733.33,1.0,ltr,NaN,NaN,NaN,NaN

In [25]:
for i in df_productos_original.columns:
    print(f" {i} : {df_productos_original[i].dtype}")

 id_comercio : object
 id_bandera : float64
 id_sucursal : float64
 id_producto : float64
 productos_ean : float64
 productos_descripcion : str
 productos_cantidad_presentacion : float64
 productos_unidad_medida_presentacion : str
 productos_marca : str
 productos_precio_lista : float64
 productos_precio_referencia : float64
 productos_cantidad_referencia : float64
 productos_unidad_medida_referencia : str
 productos_precio_unitario_promo1 : float64
 productos_leyenda_promo1 : str
 productos_precio_unitario_promo2 : float64
 productos_leyenda_promo2 : float64

In [ ]:
with zipfile.ZipFile("sepa_viernes.zip",'r') as zip_general:
    lista_zips = zip_general.namelist()
    print(lista_zips)

['2026-05-29/', '2026-05-29/sepa_2_comercio-sepa-10_2026-05-29_01-05-08.zip', '2026-05-29/sepa_2_comercio-sepa-6_2026-05-29_01-05-08.zip', '2026-05-29/sepa_2_comercio-sepa-5_2026-05-29_01-05-08.zip', '2026-05-29/sepa_2_comercio-sepa-36_2026-05-29_01-05-08.zip', '2026-05-29/sepa_1_comercio-sepa-9_2026-05-29_09-05-10.zip', '2026-05-29/sepa_1_comercio-sepa-21_2026-05-29_09-05-10.zip', '2026-05-29/sepa_1_comercio-sepa-20_2026-05-29_09-05-10.zip', '2026-05-29/sepa_1_comercio-sepa-3_2026-05-29_09-05-10.zip', '2026-05-29/sepa_1_comercio-sepa-8_2026-05-29_09-05-10.zip', '2026-05-29/sepa_2_comercio-sepa-2_2026-05-29_01-05-08.zip', '2026-05-29/sepa_1_comercio-sepa-13_2026-05-29_09-05-10.zip', '2026-05-29/sepa_1_comercio-sepa-12_2026-05-29_09-05-10.zip', '2026-05-29/sepa_1_comercio-sepa-19_2026-05-29_09-05-10.zip', '2026-05-29/sepa_1_comercio-sepa-4_2026-05-29_09-05-10.zip', '2026-05-29/sepa_1_comercio-sepa-23_2026-05-29_09-05-10.zip', '2026-05-29/sepa_1_comercio-sepa-47_2026-05-29_09-05-10.zip', '2026-05-29/sepa_1_comercio-sepa-16_2026-05-29_09-05-10.zip', '2026-05-29/sepa_2_comercio-sepa-11_2026-05-29_01-05-08.zip', '2026-05-29/sepa_1_comercio-sepa-15_2026-05-29_09-05-10.zip']

In [7]:
# Agarramos la ruta del primer supermercado de tu lista
primer_super_ruta = lista_zips[1]

# Volvemos a abrir el ZIP general
with zipfile.ZipFile("sepa_viernes.zip", 'r') as zip_general:
    # Abrimos el ZIP interno como un archivo virtual en la RAM
    with zip_general.open(primer_super_ruta) as archivo_virtual:
        # Pasamos ese archivo virtual a zipfile para leer su contenido
        with zipfile.ZipFile(archivo_virtual) as zip_interno:
            # Imprimimos los archivos que tiene adentro ese supermercado
            print(zip_interno.namelist())

['productos.csv', 'comercio.csv', 'sucursales.csv']

In [ ]:
with zipfile.ZipFile("sepa_viernes.zip", "r") as zip_general:
    lista_zips = zip_general.namelist()
    with zip_general.open(lista_zips[1]) as archivo_virtual:
        with zipfile.ZipFile(archivo_virtual) as zip_interno:
            name_csv = [n for n in zip_interno.namelist() if 'productos' in n.lower()][0]
            with zip_interno.open(name_csv) as producto_csv:
                
                df_provisorio = pd.read_csv(producto_csv, sep="|", dtype={
                'id_producto': str,     
                'id_comercio': str,     
                'id_bandera': str,      
                'id_sucursal': str      
                })
        
            df_productos = df_provisorio[['productos_ean', 'productos_descripcion', 'productos_marca', "id_producto"]]

C:\Users\user\AppData\Local\Temp\ipykernel_4128\937725100.py:7: DtypeWarning: Columns (0: id_comercio) have mixed types. Specify dtype option on import or set low_memory=False.
  df_provisorio = pd.read_csv(producto_csv, sep="|")

In [13]:
df_productos.head()

,productos_ean,productos_descripcion,productos_marca,id_producto
0,1.0,MIX CROCANTE CARREFOUR CLASSIC X 40 GRS,CARREFOUR CLASSIC,7.791720e+12
1,1.0,PAN ROSETA CONGELADA MAMA COCINA X 6 U,MAMA COCINA,7.792180e+12
2,1.0,SHAMPOO RECONSTRUCCION COMPLETA DOVE X 400 CC,DOVE,7.791293e+12
3,1.0,ACONDICIONADOR LISO EFECTO BOTOX TRESEMME X 25...,TRESEMME,7.791293e+12
4,1.0,PAPAS CONGELADAS PRECOCIDAS SWIFT BOLSA X 700 GRM,SWIFT,7.790361e+12